version: '3.8'

services:
  userms_db:
    image: postgres:11.8
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=assignment_local